background {
    monitor =
    color = rgb(1e1e2e)
}

general {
    disable_loading_bar = true
    no_fade_in = true
    no_fade_out = true
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    outer_color = rgb(1e1e2e)
    inner_color = rgb(313244)
    font_color = rgb(cdd6f4)
    fade_on_empty = true
    placeholder_text = <i>Lösenord...</i>
    hide_input = false
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = Hej, $USER
    color = rgb(cdd6f4)
    font_size = 24
    font_family = Sans
    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(cdd6f4)
    font_size = 64
    font_family = Sans Bold
    position = 0, 200
    halign = center
    valign = center
}
