# Path to your oh-my-zsh installation.
export ZSH=/home/jonas/.oh-my-zsh

ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-completions
)

source $ZSH/oh-my-zsh.sh

source ~/.zsh_profile
if [ -d "${HOME}/.local/zsh" ] && [ -s "${HOME}/.local/zsh/profile" ]; then
  source ~/.local/zsh/profile
fi

shared_zsh_profile="${HOME}/.config/zsh/profile"
shared_zsh_aliases="${HOME}/.config/zsh/aliases"
if [ -s "${shared_zsh_profile}" ]; then
  source "${shared_zsh_profile}"
fi
if [ -s "${shared_zsh_aliases}" ]; then
  source "${shared_zsh_aliases}"
fi

export PATH="$HOME/.local/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

autoload -U add-zsh-hook
load-nvmrc() {
  local node_version="$(nvm version)"
  local nvmrc_path="$(nvm_find_nvmrc)"

  if [ -n "$nvmrc_path" ]; then
    local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

    if [ "$nvmrc_node_version" = "N/A" ]; then
      nvm install
    elif [ "$nvmrc_node_version" != "$node_version" ]; then
      nvm use
    fi
  elif [ "$node_version" != "$(nvm version default)" ]; then
    echo "Reverting to nvm default version"
    nvm use default
  fi
}
add-zsh-hook chpwd load-nvmrc
load-nvmrc
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
